import numpy as np

output = {}
branches = {#"run": np.int64,
            "event": np.int64,
            #"lumi": np.int64,
            "nmuons": int,
            "nelectrons": int,
            "nleptons": int,
            "nbjets_loose": int,
            "nbjets_medium": int,
            "njets": int,
            "met_pt": float,
            "met_phi": float,
            "mu1_fromH_pt": float,
            "mu1_fromH_eta": float,
            "mu1_fromH_phi": float,
            "mu2_fromH_pt": float,
            "mu2_fromH_eta": float,
            "mu2_fromH_phi": float,
            "H_pt": float,
            "H_eta": float,
            "H_phi": float,
            "H_mass": float,
            "jet1_pt": float,
            "jet1_eta": float,
            "jet1_phi": float,
            "jet1_mass": float,
            "jet2_pt": float,
            "jet2_eta": float,
            "jet2_phi": float,
            "jet2_mass": float,
            "dijet_mass": float,
            "dijet_eta": float,
            "dijet_pt": float,
            "dijet_phi": float,
            "mumuH_dR": float,
            "mu1_mu2_dphi": float,
            "mu1_fromH_ptErr": float,
            "mu2_fromH_ptErr": float,
            "pt_rc_1": float,
            "pt_rc_2": float,
            "y_star": float,
            "z_star": float,
            "R_pT": float,
            "diMu-mass_resolution": float,
            "diMu_pt_rc": float,
            "diMu_eta_rc": float,
            "diMu_phi_rc": float,
            "diMu_mass_rc": float,
            "diMufsr_pt": float,
            "diMufsr_eta": float,
            "diMufsr_phi": float,
            "diMufsr_mass": float,
            "diMufsr_rc_pt": float,
            "diMufsr_rc_eta": float,
            "diMufsr_rc_phi": float,
            "diMufsr_rc_mass": float,
            "weight": float,
            "eventWeight": float,
            "trg_single_mu24": bool,
            #"genWeight": float,
            #"puWeight": float,
            "SoftActivityJetNjets5": int,
            #"jet1_qgl": float,
            #"jet2_qgl": float,
            "diMu-mass_resolution_abs": float,
            "log_dijet_mass": float,
            "log_diMufsr_rc_pt": float,
            "min_delta_eta_dimu_jets": float,
            "delta_eta_jj": float,
}


#for branch in branches:
#    output[branch] = np.array([])
#    #output[branch] = []

